name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for publishing'
        required: true
        default: '1.0-SNAPSHOT'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add execute permission to gradlew
        run: chmod +x gradlew

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload to maven
        if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
        env:
          CI: true
          VERSION: ${{ github.event.inputs.version || '1.0-SNAPSHOT' }}
          GITHUB_TOKEN: ${{ secrets.PACKAGE_SECRET }}
          JITPACK_TOKEN: ${{ secrets.JITPACK_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run:
          ./gradlew publish